### Importing & Exploring Data

### We will import pandas as we will use it in dataset importing

In [1]:
import pandas as pd #save data in dataframes to quickly and conveniently manipulate and access large amounts of data
df = pd.read_csv("creditcard.csv") #import our data from the csv file

### We will do some exploratory for data

In [2]:
df.head() #check first 5 rows in our dataset

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
df.describe() #To have a quick overview on our data statistics parameters such as (mean, std, min, max, quantile values..etc) 

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  3.919560e-15  5.688174e-16 -8.769071e-15  2.782312e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean  -1.552563e-15  2.010663e-15 -1.694249e-15 -1.927028e-16 -3.137024e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.537294e-16  7.959909e-16  5.367590e-16  4.458112e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   1.453003e-15  1.699104e-15 -3.660161e-16 -1.206049e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [4]:
df.columns  #get a list for all columns names in order we need to get to any of them

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [5]:
df.Class.value_counts()   #We Will check the balancing of your data Non-fraud (0) vs Fraud (1)

0    284315
1       492
Name: Class, dtype: int64

#### We notice that we have a very large imbalance in our data as most of the transactions are non fraud and only about 0.2% of the transaction are fraud which will lead to lack in accuracy of the models so we will try some solutions for this issue

### We will divide the data into X and Y, X will be features and Y will be the output (Fraud, Non-Fraud)

In [6]:
X = df.iloc[:,:-1] #Assign all columns except the last one (Class) will be our features
y = df.iloc[:,-1] #Assign (Class) columns to be our target column 

## Base Models

### We will use some Sklearn Models and check accuracy of all of them after each Model


In [7]:
from sklearn.linear_model import LogisticRegression #Import Logistic Regression from Sklearn
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
#Import accuracy_score (we use it to cacluate subset accuray)
#Import confusion matrix (used to evaluate the quality of the output of a classifier on the data set)
#Import classification report (used to show the precision, recall, F1 Score, and support for trained classification model)
from sklearn.model_selection import KFold #import KFLOD corss validator 
import numpy as np #import #save data in arrays for quick computations
from sklearn.model_selection import GridSearchCV #import GridSearchCV to hypertuning the model
from sklearn.model_selection import train_test_split #will split our data for us

## Logistic Regression

### Logistic regression is one of primary models that we usually we use in first place in classifications cases!, and we will use KFold cross validation technique

In [8]:
log_class = LogisticRegression() #import logisticrgressor
grid = {'C': 10.0 ** np.arange(-2, 3), 'penalty': ['l1', 'l2']} #Grid parameter we will use in GridSearch
cv = KFold(n_splits=5, shuffle=False, random_state=None) #Cross validation spliting strategy we will use in GridSearch

### Spliting our Data

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7) #splitting for our data with 70% to be a test size

In [10]:
clf = GridSearchCV(log_class, grid, cv=cv, n_jobs=-1, scoring='f1_macro') #GridSearchCV we will use in Tuning of our parameter
clf.fit(X_train, y_train) #Use Training data to tune our parameter

C:\Users\mahmm\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.79356779        nan 0.81571109        nan 0.82285672
        nan 0.81245865        nan 0.82876034]
  warnings.warn(
C:\Users\mahmm\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

### Getting confusion Matrix and accuracy score

In [11]:
prediction = clf.predict(X_test) #Use our Model to predict the test data
print(confusion_matrix(y_test, prediction)) #Print confusion matrix between actual test data and predicted data
print(accuracy_score(y_test, prediction)) #Print accuracy score between actual test data and predicted data
print(classification_report(y_test, prediction)) #Print Classification report between actual test data and predicted data

[[198923    112]
 [    91    239]]
0.9989817671105761
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199035
           1       0.68      0.72      0.70       330

    accuracy                           1.00    199365
   macro avg       0.84      0.86      0.85    199365
weighted avg       1.00      1.00      1.00    199365



#### For our First logisticregression model we got the follwing results: True Positive = 198927, False Positive = 77, True Negative = 161, False Negative = 200 
#### in our case the most important parameter is to have the less False negative value (Fraud Cases detected as non Fraud) which = 161 which is a big value!

### Next We will use RandomForset Model

## RandomForestClassifier

In [12]:
class_weight = dict({0:1, 1:100}) #This is class_weight attribute value we will use in RandormfroestClassifier

In [13]:
from sklearn.ensemble import RandomForestClassifier #importing RandomfroestClassifier from Sklearn
clf = RandomForestClassifier(class_weight=class_weight) #asssigning regressor
clf.fit(X_train, y_train) #Training our RandomForestRegressor

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [14]:
prediction = clf.predict(X_test) #Predicting our test data
print(confusion_matrix(y_test, prediction)) #Printing confusion matrix
print(accuracy_score(y_test, prediction)) #Printing accuracy score
print(classification_report(y_test, prediction)) #Printing Classification Report

[[199022     13]
 [    74    256]]
0.9995636144759612
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199035
           1       0.95      0.78      0.85       330

    accuracy                           1.00    199365
   macro avg       0.98      0.89      0.93    199365
weighted avg       1.00      1.00      1.00    199365



### As we have a very small values of Fraud cases it's recomended to take equlas samples to help models in detecting the pattern

## Under Sampling

In [15]:
!pip install imblearn

  Using cached imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
  Using cached imbalanced_learn-0.8.0-py3-none-any.whl (206 kB)


In [16]:
from imblearn.under_sampling import NearMiss #importing NearMiss undersampling 
from collections import Counter #importing Counter from collection we will use it in counting data

In [17]:
ns = NearMiss(0.8) #Desired ratio for undersampling
X_train_ns, y_train_ns = ns.fit_resample(X_train, y_train) #getting new resampled training data

C:\Users\mahmm\anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [18]:
print("The number of classes before fit {}".format(Counter(y_train))) #number of class before resample
print("The number of classes after fit {}".format(Counter(y_train_ns))) #number of class after resample

The number of classes before fit Counter({0: 85280, 1: 162})
The number of classes after fit Counter({0: 202, 1: 162})


In [19]:
from sklearn.ensemble import RandomForestClassifier #importing RandomForestClassifier 
clf = RandomForestClassifier() #Assign Classifier
clf.fit(X_train_ns, y_train_ns) #Training with resampled data

RandomForestClassifier()

In [20]:
prediction = clf.predict(X_test) #Predicting Test Data
print(confusion_matrix(y_test, prediction)) #Printing Cofusion Matrix
print(accuracy_score(y_test, prediction)) #Printing Accuracy Matrix
print(classification_report(y_test, prediction)) #Printing Classification Report

[[199022     13]
 [    74    256]]
0.9995636144759612
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199035
           1       0.95      0.78      0.85       330

    accuracy                           1.00    199365
   macro avg       0.98      0.89      0.93    199365
weighted avg       1.00      1.00      1.00    199365



### Over-Sampling

In [21]:
from imblearn.over_sampling import RandomOverSampler #Import Oversampling module
os = RandomOverSampler(0.5) #Choosing ratio for oversampling
X_train_os, y_train_os = os.fit_resample(X_train, y_train) #Producing new oversampling Data
print("The number of classes before fit{}".format(Counter(y_train_os))) #counting the number after over sampling

The number of classes before fitCounter({0: 85280, 1: 42640})


C:\Users\mahmm\anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [23]:
from sklearn.ensemble import RandomForestClassifier #Importing Random Forest Classifier
clf = RandomForestClassifier() #Assign Classifier
clf.fit(X_train_os, y_train_os) #Training our Classifier

RandomForestClassifier()

In [24]:
prediction = clf.predict(X_test) #Predicting Test Data
print(confusion_matrix(y_test, prediction)) #Printing Confusion Matrix
print(accuracy_score(y_test, prediction)) #Printing Accuracy Matrix
print(classification_report(y_test, prediction)) #Printing Classification Report

[[199017     16]
 [    79    253]]
0.9995234870714519
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199033
           1       0.94      0.76      0.84       332

    accuracy                           1.00    199365
   macro avg       0.97      0.88      0.92    199365
weighted avg       1.00      1.00      1.00    199365



## SMOTETomek


In [23]:
from imblearn.combine import SMOTETomek #importing SMOTETomek which we use for oversampling

In [28]:
os = SMOTETomek(0.5) #oversampling desired ratio
X_train_os, y_train_os = os.fit_resample(X_train, y_train) #resample our data
print("The number of classes before fit {}".format(Counter(y_train))) #counting original y data
print("The number of classes after fit {}".format(Counter(y_train_os))) #counting oversampled data

C:\Users\mahmm\anaconda3\envs\tesorflow\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classes before fit Counter({0: 85282, 1: 160})
The number of classes after fit Counter({0: 84322, 1: 41681})


In [29]:
from sklearn.ensemble import RandomForestClassifier #importing random forest classifier
clf = RandomForestClassifier()  #Assign Classifier
clf.fit(X_train_os, y_train_os) #Training our model with oversmpled data

RandomForestClassifier()

In [30]:
prediction = clf.predict(X_test) #Predict test data
print(confusion_matrix(y_test, prediction)) #Print confusion matrix
print(accuracy_score(y_test, prediction)) #Print accuracy matrix
print(classification_report(y_test, prediction)) #Print Classification report

[[198992     41]
 [    64    268]]
0.9994733278158152
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199033
           1       0.87      0.81      0.84       332

    accuracy                           1.00    199365
   macro avg       0.93      0.90      0.92    199365
weighted avg       1.00      1.00      1.00    199365



### SMOTE


In [24]:
from imblearn.over_sampling import SMOTE #Import Smote which is an oversampling technique where the synthetic samples are generated for the minority class

In [25]:
sm = SMOTE()
X_train_sm, y_train_sm = os.fit_resample(X_train, y_train) #Generating new training data
print("The number of classes before fit {}".format(Counter(y_train))) #Count Class before resample
print("The number of classes after fit {}".format(Counter(y_train_sm))) #Count Class after resample

The number of classes before fit Counter({0: 85280, 1: 162})
The number of classes after fit Counter({0: 85280, 1: 42640})


In [26]:
from sklearn.ensemble import RandomForestClassifier #Importing Random Forest Classifier
clfsm = RandomForestClassifier() #Assign Classifier
clfsm.fit(X_train_sm, y_train_sm) #Training our model

RandomForestClassifier()

In [27]:
prediction = clfsm.predict(X_test) #Predict Test Data
print(confusion_matrix(y_test, prediction)) #Print confusion matrix
print(accuracy_score(y_test, prediction)) #Print accuracy score
print(classification_report(y_test, prediction)) #Print Classification report

[[199019     16]
 [    67    263]]
0.9995836781782158
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199035
           1       0.94      0.80      0.86       330

    accuracy                           1.00    199365
   macro avg       0.97      0.90      0.93    199365
weighted avg       1.00      1.00      1.00    199365



### Extra-Trees Classifier

In [28]:
from sklearn.ensemble import ExtraTreesClassifier
#importing Extra Tree Classifier which is a type of ensemble learning technique which aggregates the results of multiple de-correlated decision trees collected in a “forest” to output it's classification result
clfsm = ExtraTreesClassifier() #Assigin Classifier
clfsm.fit(X_train_sm, y_train_sm) #Train our Model

ExtraTreesClassifier()

In [29]:
prediction = clfsm.predict(X_test) #Predict our data
print(confusion_matrix(y_test, prediction)) #Print Confusion Matrix
print(accuracy_score(y_test, prediction)) #Print Accuracy Score
print(classification_report(y_test, prediction)) #Print Classification Report

[[199017     18]
 [    69    261]]
0.9995636144759612
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199035
           1       0.94      0.79      0.86       330

    accuracy                           1.00    199365
   macro avg       0.97      0.90      0.93    199365
weighted avg       1.00      1.00      1.00    199365



# Conculison 

## After trying many models we have decided to go with RandomforestClassifier with undersampling as it's the lowest one that missing a Fraud (False Negative) but it have the worst results for detecting Non Fraud as Fraud (False positive).

## But you can consider it as a trade off as it would be better to suspect more Non Fraud as Fraud rather than letting fraud operations happen!